### ISSUE TITLE
(SNAPSHOT) Webserver won't start on non-default port.

### ISSUE THREAD

**Issue by EsserGaming** [BlueMap-Minecraft/BlueMapVue#9]
I am using the latest snapshot of bluemap and when I change the port for the webserver it fails to bind but then when I use the default _8100_ it is just fine. Keep in mind I have DMZ'd the server and every port is open.

**Comment by TBlueF** [comment]
Webserver is [BlueMap](https://github.com/BlueMap-Minecraft/BlueMap), so this is the wrong issue-tracker ^^
Also there are exactly no changes at all on the webserver between 1.3.1 and 1.4.0, so this is very likely an issue on your end.

Closing since its the wrong project and please use the discord for support 😋
